apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-app
spec:
  selector:
    matchLabels:
      app: configuration-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: configuration-pod
    spec:
      containers:
        - name: configuration-container
          image: ""
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Staging"
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  selector:
    app: configuration-pod
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: configuration-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: configuration-app
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50


